package src;

/**
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 *
 *
 *
 * Example 1:
 *
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * Example 2:
 *
 * Input: s = "", t = "y"
 * Output: "y"
 *
 *
 * Constraints:
 *
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lowercase English letters.
 */

public class L389_FindDifference {
    public char findTheDifference(String s, String t) {
        int[] dp = new int[26];
        for(int i = 0;i<s.length();i++){ // firstly we are counting, all the elements of the 's' string
            dp[s.charAt(i)-97]++;
        }

        for(int i = 0;i<s.length();i++){ // subtracting all those elements count
            if(dp[t.charAt(i)-97] == 0){ // if the count is already zero, mean this element is only extra in count
                return t.charAt(i);
            }else{
                dp[t.charAt(i)-97]--;
            }
        }

        return t.charAt(s.length()); // if compiler comes here, mean the last element is the only element which is extra in count
    }
}
